language:        python
cache:           pip
dist:            xenial

matrix:
  include:
    - python:    3.6
      env:       TOXENV=py36
    - python:    3.7
      env:       TOXENV=py37
    - python:    3.8
      env:       TOXENV=py38
    - python:    3.6
      env:       TOXENV=docs
    - python:    3.6
      env:       TOXENV=coverage
    - python:    3.6
      env:       TOXENV=coveralls

branches:
  only:
    - master
    - develop

before_install:
  - echo $TRAVIS_PYTHON_VERSION

install:
  - pip install tox-travis
  - pip install coverage
  - pip install coveralls
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

script:
  - tox

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - stefan.kasberger@univie.ac.at
    on_success:  change
